config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    # validates :name, :email, :phone , :twitter, presence: true
    # validates_uniqueness_of :email, on: [:create , :update], message: "must be unique"

    belongs_to :user,optional: true

    scope :search, ->(search) {
        if search
            where("name LIKE ? OR users.email LIKE ?", "%#{search}%", "%#{search}%")
        end
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.eager_load(:user).search(params[:search]).paginate(page: params[:page],per_page:10)
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    if user_signed_in?
      @friend = current_user.friends.create(friend_params)
    else
      @friend = Friend.new(friend_params)
    end

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    friend_update_params = friend_params
    friend_update_params[:user_id] = current_user&.id
    respond_to do |format|
      if @friend.update(friend_update_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id:params[:id])

    if @friend.nil?
      respond_to do |format|
        format.html { redirect_to friends_url, notice: "Not Authorized , Owner Only Permission" }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:name, :email, :phone, :twitter)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,class:"form-control",placeholder:'Enter name' %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email,class:"form-control",placeholder:'Enter email' %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone,class:"form-control",placeholder:'Enter phone' %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter,class:"form-control",placeholder:'Enter twitter' %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <th scope="row">

      <%= link_to friend.id, friend %>

    
  </th>

  <td>
  <%= friend.name %>
  </td>

  <td>
   
    <%= friend.email %>
  </td>

  <td>
   
    <%= friend.phone %>
  </td>

  <td>
   
    <%= friend.twitter %>
  </td>
  <td>
    <%= friend&.user&.email %>
  </td>
  <td>
    <div class="row ">
    <%= link_to "Edit", edit_friend_path(friend),class:'col align-self-center' %> 
    <div class="col align-self-center">
     <%= button_to "Delete", friend, method: :delete,class:"btn btn-link" %>
    </div>
   
    </div>
  </td>

</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend,class:"btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path,class:"btn btn-outline-secondary" %>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<div id="friends">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend| %>
    <%= render friend %>
  <% end %>
  </tbody>
  </table>
  <div class="apple_pagination">
    <%= will_paginate @friends, :container => false %>
  </div>
</div>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3 mt-3"  id="<%= dom_id @friend %>">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold ">  <%= @friend.name %></h1>
        <p class="col-md-8 fs-4">
        
        </p>
        <table class="table col-md-8 fs-4">
  
  <tbody>
    <tr>
    
      <td>Email</td>
     <td> <%= @friend.email %></td>
    
    </tr>
    <tr>
    
      <td>Phone</td>
     <td> <%= @friend.phone %></td>
    
    </tr>
     <tr>
    
      <td>Twitter</td>
     <td> <%= @friend.twitter %></td>
    
    </tr>
    
   
  </tbody>
</table>
        <%= button_to "Destroy this friend", @friend, method: :delete,class:"btn btn-danger" %>
      </div>
    </div>
<div>

</div>


<div>
 <div class="mb-3">
  <%= link_to "Edit this friend", edit_friend_path(@friend),class:"btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path,class:"btn btn-outline-secondary" %>
 </div>

 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Frient App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>


        <% end %>
      </ul>
      <%= form_tag request.path, :method => 'get', class: "d-flex" do %>
        <%= text_field_tag :search,params['search'],class:"form-control me-2",type:"Search",placeholder:"Search" %>
        <button class="btn btn-outline-success" type="submit">Search</button>
      <% end %>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Hello About</h1>

app/views/home/index.html.erb
<h1>HELLO WORLD</h1>

app/views/layouts/_alert.html.erb
<% if notice %>
<br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<% if alert %>
<br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Hello, world!</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<%= render 'home/header' %>
<div class="container">
  <%= render('layouts/alert') %>
  <%= yield %>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>